### ISSUE TITLE
disable the extension

### ISSUE THREAD

**Issue by majaesch** [quarkiverse/quarkus-rabbitmq-client#56]
There is no option to disable the extension.

A running rabbitMQ server at start time is needed, even if I don't want to send or receive messages.

I would like to see a "quarkus.rabbitmqclient.enabled" which I can set to "false". So I can deploy to environments, which do not have a running mq server.

**Comment by bpasson** [comment]
Thank you for taking the time to create this ticket. It is not completely clear to me what you want to achieve with this option. What would be the expected behavior? The injected RabbitMQClient connects to a RabbitMQ broker upon calling `RabbitMQClient.connect()`. If this method is never called it is completely safe to use in an environment without a running RabbitMQ broker.

**Comment by bpasson** [comment]
Disabling clients at build time will be supported through #73.
